services:
  # Backend Laravel
  - type: web
    name: cheap-parts-backend
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cheap-parts-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cheap-parts-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cheap-parts-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cheap-parts-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cheap-parts-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: cheap-parts-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://cheap-parts-frontend.onrender.com

databases:
  # Base de datos PostgreSQL
  - name: cheap-parts-db
    plan: free
    region: frankfurt
    databaseName: cheapparts
    user: cheapparts
